version: "3"
services:
  web:
    build: .
    env_file: .env
    environment:
      PORT: "3000"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: bin/start

  postgres:
    image: postgres:9.6.1
    ports:
      - "5433:5432"
