version: "3"
services:
  matchvote:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: bin/start
