source "https://rubygems.org"

gem "awesome_print", "~> 1.6.1"
gem "aws-sdk-rails", "~> 2.0.0"
gem "bcrypt", "~> 3.1.10"
gem "bootstrap-sass", "~> 3.3.4"
gem "carrierwave-aws", "~> 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "devise", "~> 3.4.0"
gem "haml-rails", "~> 0.9"
gem "httparty", "~> 0.13.3"
gem "jquery-rails", "~> 4.0.4"
gem "ledermann-rails-settings", "~> 2.4.0"
gem "mailgun_rails", "~> 0.9.0"
gem "omniauth", "~> 1.8.1"
gem "omniauth-facebook", "~> 4.0.0"
gem "omniauth-twitter", "~> 1.4.0"
gem "pg", "~> 0.18.1"
gem "pg_search", "~> 0.7.9"
gem "puma", "3.12.2"
gem "pundit", "~> 1.0.0"
gem "rails", "4.2.10"
gem "rails-html-sanitizer", "~> 1.0.1"
gem "react-rails", "~> 1.5.0"
gem "sass-rails", "~> 5.0.1"
gem "sdoc", "~> 0.4.0", group: :doc
gem "social-share-button", "~> 1.1.0"
gem "sprockets-coffee-react", "~> 4.0.1"
gem "sweetalert-rails", "~> 1.1.3"
gem "turbolinks", "~> 2.5.3"
gem "uglifier", "~> 2.7.1"
gem "virility", "~> 0.4.0"
gem "will_paginate", "~> 3.0.7"

group :development, :test do
  gem "benchmark-ips", "~> 2.1.1"
  gem "byebug", "~> 4.0.2"
  gem "dotenv-rails", "~> 2.0.1"
  gem "faker", "~> 1.9.1"
  gem "flamegraph", "~> 0.1.0"
  gem "rack-mini-profiler", "~> 0.10.7"
  gem "rails_db_info", "~> 0.2"
  gem "rubocop"
  gem "spring", "~> 1.3.3"
  gem "spring-commands-rspec", "~> 1.0.4"
  gem "stackprof", "~> 0.2.7"
end

group :test do
  gem "capybara", "~> 2.4.4"
  gem "database_cleaner", "~> 1.4.1"
  gem "factory_girl_rails", "~> 4.5.0"
  gem "poltergeist", "~> 1.6.0"
  gem "rspec-rails", "~> 3.2.1"
  gem "simplecov", "~> 0.10.0"
  gem "webmock", "~> 1.21.0"
end

group :production do
  gem "rails_12factor", "~> 0.0.3"
end
