default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &dev
  <<: *default
  database: matchvote_dev
  host: postgres
  port: 5432
  username: postgres

test:
  <<: *dev
  database: matchvote_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
